version: '2'

services:
    news:
        build:
            context: .
            dockerfile: ./docker/news/Dockerfile
        image: kcz17/news
        hostname: news
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - reschedule=on-node-failure
        ports:
            - "8080:80"
    news-db:
        build:
            context: ./docker/news-db/
        image: kcz17/news-db
        hostname: news-db
        restart: always
        environment:
            - reschedule=on-node-failure
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=socksdb
